### ISSUE TITLE
Kinetic - Ubuntu 16.04 - Rviz Empty

### ISSUE THREAD

**Issue by LAR-UFSC** [ethz-asl/StructuralInspectionPlanner#6]
I followed the steps to install the Structural Inspection Planner on Ubuntu Ubuntu 16.04 - ROS - Kinetic which is ok. 
I execute in the terminal: roscore / roslaunch koptplanner hoaHakanaia.launch / rosrun request hoaHakanaia (each one in different terminals) and in another rosrun rviz rviz ( this open the Rviz) but is empty.

I tried to add the necessary displays, as shown in the tutorial (https://github.com/ethz-asl/StructuralInspectionPlanner):

‘Path’ on topic ‘visualization_marker’
‘Marker’ on topic ‘viewpoint_marker’
‘Path’ on topic ‘stl_mesh’
‘Marker’ on topic ‘scenario’

But I just found to add the two first, and after add them, nothing change. Nevertheless if I type in the terminal rostopic list  /stl_mesh and /scenario appear. 

In fact,I can put this four displays (‘Path’ on topic ‘visualization_marker’; ‘Marker’ on topic ‘viewpoint_marker’; ‘Path’ on topic ‘stl_mesh’; ‘Marker’ on topic ‘scenario’) if I make a little trick, which means if after done all the informations on the terminal when the Rviz open I insert the displays in the inverse order... first scenario then stl_mesh; 
When I add the ‘Marker’ on topic ‘viewpoint_marker’ appear a error, because the Rviz started with Fixed Frame 'map'. Is do not have option to change but I can right there to /kopt_frame and add ‘Marker’ on topic ‘viewpoint_marker’ again and do not have more the error signal.
But the display still empty. I tried it with different models of the demo and happens the same thing.

And as the attached print screen appear a Fixed Frame message: "No tf data. Actual error: Fixed Frame [kopt_frame] does not exist"

Have someone use the  Structural Inspection Planner in Ubuntu 16.04 with ROS kinetic ? Is necessary
 to change anything ?

<img width="1129" alt="screen shot 2017-01-13 at 3 34 00 pm" src="https://cloud.githubusercontent.com/assets/25135264/21963799/5784f1ec-daf5-11e6-8224-29fbb021a8ec.png">

<img width="479" alt="screen shot 2017-01-13 at 3 59 31 pm" src="https://cloud.githubusercontent.com/assets/25135264/21963804/6523cd64-daf5-11e6-8b92-73ff890c8316.png">
<img width="691" alt="screen shot 2017-01-13 at 3 59 57 pm" src="https://cloud.githubusercontent.com/assets/25135264/21963805/65248c40-daf5-11e6-88f1-65bcd8d5114d.png">
<img width="1138" alt="screen shot 2017-01-13 at 4 18 06 pm" src="https://cloud.githubusercontent.com/assets/25135264/21963806/65252f1a-daf5-11e6-8436-23caa86a837a.png">

**Comment by birchera** [comment]
Hi @LAR-UFSC, thanks for posting the issue.

Structural Inpsection Planner is tested under Indigo and Jade. I haven't personally tested it with Kinetic. So this could well be a porting issue.

First thing I noted: The display 'Path' should have a buffer length >>1. In the demo scenarios I used 10000. In any case it should be greater than the number of edges in the mesh. You can check [here](https://github.com/ethz-asl/StructuralInspectionPlanner/wiki/Demo-Scenarios) for the correct setup.

I did not quite get that with the global frame. It should be set to `/kopt_frame`. Also note that Rviz needs to be configured before running the planner.

**Comment by LAR-UFSC** [comment]
The problem was the setup of the Rviz, I have to do it manually. After that, works.
