### ISSUE TITLE
[ERROR] [1484648484.484819948]: Error occured! ID: 3

### ISSUE THREAD

**Issue by LAR-UFSC** [ethz-asl/StructuralInspectionPlanner#7]
I started to use your package, for the demo scenarios it works well, after solve the things shown in other issue. Although now I tried with a model create by myself ( in fact is a relief of a place here in Spain). I keep the same configuration (rotorcraft, as installed), include the file call in the CMakeList, generate the four files as the demo scenarios. 

In the terminal: roscore / roslaunch koptplanner lamarrador.launch / rosrun request Lamarrador / rosrun rviz rviz ( Eacha one in a different terminal).

I can see in the Rviz the mesh, the arrows and then stop.

In the terminal with: roslaunch koptplanner lamarrador.launch
Appear this message:

process[Inspection_Planner-1]: started with pid [3159]
[ INFO] [1484648442.444139805]: Service started
[ INFO] [1484648484.121543533]: Request received
[ INFO] [1484648484.124552668]: STARTING ITERATION 0
[ERROR] [1484648484.484819948]: Error occured! ID: 3

And in the terminal with:  rosrun request Lamarrador
Appear this message:

[ERROR] [1484648484.493207371]: Failed to call service planner

Is there any require to the planner that I should call ? Or any other file I must create ?

At first I thing could be my mesh was so big (550000 faces) bur I Simplify to 500 to test and happens the same problem.

I`m using Ubuntu 16.04 - ROS Kinetic in a VMware Fusion.

<img width="455" alt="screen shot 2017-01-17 at 11 55 24 am" src="https://cloud.githubusercontent.com/assets/25135264/22017842/c25b67fa-dc60-11e6-987e-5e12b0aa9911.png">

<img width="1137" alt="screen shot 2017-01-17 at 11 55 33 am" src="https://cloud.githubusercontent.com/assets/25135264/22017841/c259ee20-dc60-11e6-84ed-6abebdc748d9.png">

**Comment by birchera** [comment]
The error message you get [says](https://github.com/ethz-asl/StructuralInspectionPlanner/blob/7f4d851063a3e97b13b78cc80f9889aa68299ffd/koptplanner/include/koptplanner/plan.hpp#L53) that one of the viewpoints was not feasible. This can easily happen for complicated structures and is very sensitive to other parameters like field of view, incidence angle or min/max distance. As an example, a front looking camera with a small field of view is not suitable for inspection of horizontal surfaces, especially in presence of an incidence angle constraint.

You also have to take care when simplifying the mesh. Many implementations of such algorithms that I have seen tend to create some facets with normals that point in directions you would not expect. This could easily render the problem infeasible under given constraints.
