### ISSUE TITLE
No file "inspection.h"

### ISSUE THREAD

**Issue by anwesha94** [ethz-asl/StructuralInspectionPlanner#8]
I was trying to execute the source code plan.cpp but it shows that the header file "koptplanner/inspection.h" does not exist.I checked the file is not in the repository. Can it be made available?
Thank you.
-Anwesha

**Comment by birchera** [comment]
Did you install and build according to the [install instructions](https://github.com/ethz-asl/StructuralInspectionPlanner/wiki/Installation-Instructions)?

The inspection.h is an auto-generated file from the rosservice [file](https://github.com/ethz-asl/StructuralInspectionPlanner/wiki/Installation-Instructions).

**Comment by anwesha94** [comment]
What are the exact steps for build?
I tried launching it by opening two shells as instructed. It shows the following error:
1] kopt.launch is neither a launch file in package [koptplanner] nor is [koptplanner] a launch file name
2][rospack] Error: package 'request' not found

**Comment by birchera** [comment]
The installation instructions are according to the install instructions linked in my last post.

Specifically, you may miss the step of
```sh
source devel/setup.bash
```

**Comment by anwesha94** [comment]
I didn't miss that step. I thought there is more to the build instructions where it is written "build process should then be executed".

**Comment by birchera** [comment]
It is possible that the instructions are not totally precise. Can you verify that the packages are on your ROS_PACKAGE_PATH? Check [this page](http://wiki.ros.org/ROS/Tutorials/InstallingandConfiguringROSEnvironment) for reference.

**Comment by anwesha94** [comment]
I checked ROS_PACKAGE_PATH. My current directory was not included in that path. After I added it, I was able to run: roslaunch koptplanner kopt.launch
"rosrun request request" however generated the following error:
[rosrun] couldn't find executable named request below /home/../../catkin_ws_repos/src/StructuralInspectionPlanner/request

**Comment by anwesha94** [comment]
Hi,
I was able to run the two commands successfully after sourcing and updating the ROS_PACKAGE_PATH env variable.
Thanks a lot.
